export const jobs = [
	{
		id: 1,
		companyName: "Infosys",
		jobCategory: "Technical",
		jobDesignation: "Tester",
		jobLocation: "Bangalore, Karnatakka",
		salary: "30,000 - 40,000",
		numberOfOpenings: 10,
		skillsRequired: ["HTML", "CSS", "JavaScript"],
		applyBy: "2024-01-15",
		jobPosted: 1706186420461,
		applicants: [
			{
				name: "Ram",
				email: "ram@gmail.com",
				contact: "9129403889",
				resumePath: "/uploads/1706180261132-Guided Paths.pdf",
			},
		],
	},
	{
		id: 2,
		companyName: "TechSolutions",
		jobCategory: "Development",
		jobDesignation: "Software Engineer",
		jobLocation: "Hyderabad, Telangana",
		salary: "50,000 - 60,000",
		numberOfOpenings: 8,
		skillsRequired: ["Java", "Spring Boot", "MySQL"],
		applyBy: "2024-02-15",
		jobPosted: 1705146410461,
		applicants: [],
	},
	{
		id: 3,
		companyName: "DataInnovators",
		jobCategory: "Data Science",
		jobDesignation: "Data Analyst",
		jobLocation: "Mumbai, Maharashtra",
		salary: "40,000 - 50,000",
		numberOfOpenings: 5,
		skillsRequired: ["Python", "SQL", "Data Visualization"],
		applyBy: "2024-03-25",
		jobPosted: 1703146410461,
		applicants: [],
	},
	{
		id: 4,
		companyName: "DesignCrafters",
		jobCategory: "Design",
		jobDesignation: "Graphic Designer",
		jobLocation: "Pune, Maharashtra",
		salary: "35,000 - 45,000",
		numberOfOpenings: 6,
		skillsRequired: ["Adobe Illustrator", "Photoshop", "UI/UX"],
		applyBy: "2024-01-15",
		jobPosted: 1705146410461,
		applicants: [],
	},
	{
		id: 5,
		companyName: "EcoSolutions",
		jobCategory: "Environmental Science",
		jobDesignation: "Environmental Engineer",
		jobLocation: "Chennai, Tamil Nadu",
		salary: "55,000 - 65,000",
		numberOfOpenings: 3,
		skillsRequired: [
			"Environmental Impact Assessment",
			"Climate Modeling",
			"Sustainability",
		],
		applyBy: "2024-01-15",
		jobPosted: 1705146410461,
		applicants: [],
	},
	{
		id: 6,
		companyName: "HealthWellness",
		jobCategory: "Healthcare",
		jobDesignation: "Registered Nurse",
		jobLocation: "Delhi, NCR",
		salary: "45,000 - 55,000",
		numberOfOpenings: 7,
		skillsRequired: [
			"Nursing Certification",
			"Patient Care",
			"Medical Record Keeping",
		],
		applyBy: "2024-01-15",
		jobPosted: 1705146410461,
		applicants: [],
	},
];

export const skills = [
	"HTML",
	"CSS",
	"JavaScript",
	"ReactJS",
	"NodeJS",
	"Python",
	"SQL",
	"Data Visualization",
	"Java",
	"Spring Boot",
	"MySQL",
	"Communication",
	"Testing",
	"Data Science",
	"Embedded Systems",
	"Cloud Management",
	"Blockchain development",
	"App development",
	"Software Development",
	"Adobe Illustrator",
	"Photoshop",
	"UI/UX",
	"Environmental Impact Assessment",
	"Climate Modeling",
	"Sustainability",
	"Nursing Certification",
	"Patient Care",
	"Medical Record Keeping",
];

